name: Maven Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn -s $GITHUB_WORKSPACE/settings.xml --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ vars.ACTIONS_MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.ACTIONS_MAVEN_TOKEN }}
